language: crystal

addons:
  apt:
    packages:
      - mosquitto

script:
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - source $HOME/.cargo/env
  - git submodule update --init --recursive
  - (cd hermes-protocol && cargo build -p hermes-mqtt-ffi -p hermes-ffi-test --release)
  - cp ./hermes-protocol/target/release/libhermes_mqtt_ffi.so .
  - crystal sam.cr -- test
  - crystal tool format --check
